import os
import logging
from typing import List, Dict, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from dotenv import load_dotenv

# Load .env if present (useful for local development)
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("chatbot_backend")

# App metadata and OpenAPI tags
openapi_tags = [
    {
        "name": "Chat",
        "description": "Endpoints for interacting with the AI chatbot.",
    },
    {
        "name": "Documentation",
        "description": "Project-level docs and usage notes.",
    },
]

app = FastAPI(
    title="Chatbot Backend API",
    description="A FastAPI backend that proxies chat requests to OpenAI and returns assistant replies.",
    version="1.0.0",
    openapi_tags=openapi_tags,
)

# CORS configuration: allow requests from the React frontend
# In production, set this via environment variable FRONTEND_ORIGIN for stricter policy.
FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "*")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[FRONTEND_ORIGIN] if FRONTEND_ORIGIN != "*" else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Validate OPENAI_API_KEY presence at startup
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
if not OPENAI_API_KEY:
    logger.warning("OPENAI_API_KEY is not set. The /api/chat endpoint will return 500 until configured.")

# Import OpenAI client
try:
    from openai import OpenAI
    openai_client: Optional[OpenAI] = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None
except Exception as e:
    logger.exception("Failed to initialize OpenAI client: %s", e)
    openai_client = None


class ChatRequest(BaseModel):
    """Input payload for chat endpoint."""
    message: str = Field(..., description="The user's latest message to the assistant.")
    conversation: Optional[List[Dict[str, str]]] = Field(
        default=None,
        description="Optional prior messages to provide conversation context, each as {role, content}."
    )
    model: Optional[str] = Field(
        default=None,
        description="Optional OpenAI model override. Defaults to gpt-3.5-turbo or equivalent."
    )
    max_history: Optional[int] = Field(
        default=8,
        description="Limit of recent messages (excluding system prompt) to pass as context."
    )


class ChatResponse(BaseModel):
    """Response payload from chat endpoint."""
    reply: str = Field(..., description="Assistant reply generated by OpenAI.")
    used_model: str = Field(..., description="The model used to generate the reply.")


def _trim_conversation(history: List[Dict[str, str]], max_history: int) -> List[Dict[str, str]]:
    """Ensure we keep only the most recent N messages for context (excluding the system prompt if provided)."""
    if not history:
        return []
    # Keep system message if present at the beginning, then take last max_history
    system_msgs = [m for m in history if m.get("role") == "system"]
    non_system = [m for m in history if m.get("role") != "system"]
    trimmed_non_system = non_system[-max_history:] if max_history and max_history > 0 else non_system
    return (system_msgs[:1] + trimmed_non_system) if system_msgs else trimmed_non_system


# PUBLIC_INTERFACE
@app.post(
    "/api/chat",
    response_model=ChatResponse,
    tags=["Chat"],
    summary="Send a message to the chatbot",
    description=(
        "Accepts a user message and optional prior conversation to generate an assistant reply using OpenAI. "
        "Returns the assistant's reply text."
    ),
    responses={
        200: {"description": "Successful response with assistant reply."},
        400: {"description": "Invalid input provided."},
        500: {"description": "Backend misconfiguration or upstream error."},
    },
)
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Chat endpoint to obtain an assistant reply via OpenAI.

    Parameters:
    - message: User's new message to the assistant.
    - conversation: Optional prior messages, each as {role: 'user'|'assistant'|'system', content: string}.
    - model: Optional OpenAI model ID to use (overrides default if provided).
    - max_history: Number of recent messages (excluding system prompt) to retain for context.

    Returns:
    - ChatResponse: { reply: string, used_model: string }

    Notes:
    - Requires the OPENAI_API_KEY environment variable to be set.
    - CORS is enabled; configure FRONTEND_ORIGIN to restrict allowed origins.
    """
    if not request.message or not request.message.strip():
        raise HTTPException(status_code=400, detail="Message must not be empty.")

    if openai_client is None:
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY is not configured. Set it in the environment to enable chat."
        )

    # Choose model with a sensible default
    model = request.model or os.getenv("OPENAI_DEFAULT_MODEL", "gpt-3.5-turbo")

    # Build messages including context
    history = request.conversation or []
    trimmed_history = _trim_conversation(history, request.max_history or 8)

    # Always append the current user message
    messages_payload: List[Dict[str, str]] = []
    # Optional: Insert a default system prompt if none exists to set assistant behavior
    if not any(m.get("role") == "system" for m in trimmed_history):
        messages_payload.append({
            "role": "system",
            "content": "You are a helpful, concise AI assistant."
        })
    messages_payload.extend(trimmed_history)
    messages_payload.append({"role": "user", "content": request.message})

    # Call OpenAI Chat Completions API
    try:
        completion = openai_client.chat.completions.create(
            model=model,
            messages=messages_payload,
            temperature=0.7,
        )
        reply_text = completion.choices[0].message.content if completion.choices else ""
        reply_text = reply_text or "I'm sorry, I couldn't generate a response."
        return ChatResponse(reply=reply_text, used_model=model)
    except Exception as e:
        logger.exception("OpenAI API error: %s", e)
        raise HTTPException(status_code=500, detail="Upstream OpenAI error. Please try again later.")


# PUBLIC_INTERFACE
@app.get(
    "/",
    tags=["Documentation"],
    summary="Service info",
    description="Simple service info endpoint. See /docs for interactive API and /openapi.json for the spec."
)
async def root() -> Dict[str, str]:
    """Root endpoint that returns basic service information."""
    return {
        "name": "chatbot_backend",
        "version": "1.0.0",
        "docs": "/docs",
        "openapi": "/openapi.json"
    }
